// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ZUIN_DEF

#ifndef _ZUIN_DEF_UI_H
#define _ZUIN_DEF_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl.h")
#include "lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"
#include "ui_Screen2.h"
#include "ui_Screen3.h"
#include "ui_Screen4.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_761137763);    // assets/desert-island_1f3dd-fe0f.png
LV_IMG_DECLARE(ui_img_1057345124);    // assets/Fire-PNG-Clipart-180x180.png
LV_IMG_DECLARE(ui_img_1448235480);    // assets/Island-icon.png
LV_IMG_DECLARE(
    ui_img_palm_trees_and_island_png_clipart_image_png);    // assets/Palm_Trees_and_Island_PNG_Clipart_Image.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
