// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ZUIN_DEF

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Island2 = NULL;
lv_obj_t * ui_Fire2 = NULL;
// event funtions
void ui_event_Screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_Screen3_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);

    ui_Island2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Island2, &ui_img_761137763);
    lv_obj_set_width(ui_Island2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Island2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Island2, 0);
    lv_obj_set_y(ui_Island2, 5);
    lv_obj_set_align(ui_Island2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Island2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Island2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Fire2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Fire2, &ui_img_1057345124);
    lv_obj_set_width(ui_Fire2, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Fire2, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Fire2, 55);
    lv_obj_set_y(ui_Fire2, 53);
    lv_obj_set_align(ui_Fire2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Fire2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Fire2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Fire2, 100);

    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Island2 = NULL;
    ui_Fire2 = NULL;

}
