// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ZUIN_DEF

#include "ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Island3 = NULL;
lv_obj_t * ui_Fire3 = NULL;
// event funtions
void ui_event_Screen3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_Screen4_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_Screen2_screen_init);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Island3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Island3, &ui_img_1448235480);
    lv_obj_set_width(ui_Island3, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Island3, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Island3, 1);
    lv_obj_set_y(ui_Island3, -1);
    lv_obj_set_align(ui_Island3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Island3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Island3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Fire3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Fire3, &ui_img_1057345124);
    lv_obj_set_width(ui_Fire3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Fire3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Fire3, 50);
    lv_obj_set_y(ui_Fire3, 42);
    lv_obj_set_align(ui_Fire3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Fire3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Fire3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Fire3, 100);

    lv_obj_add_event_cb(ui_Screen3, ui_event_Screen3, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Island3 = NULL;
    ui_Fire3 = NULL;

}
